Implement `getCapabilities`
instrumentisto/medea-flutter-webrtc pull request #137
Opened 2023-11-24 08:30 UTC by rogurotus

## Synopsis

Implement `getCapabilities`.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains issue reference
    - [x] Has type and `k::` labels applied
    - [x] Has assignee
- Before [review][l:4]:
    - [ ] Documentation is updated (if required)
    - [ ] Tests are updated (if required)
    - [ ] Changes conform [code style][l:2]
    - [ ] [CHANGELOG entry][l:3] is added (if required)
    - [ ] FCM (final commit message) is posted or updated
    - [ ] [Draft mode][l:1] is removed
- [ ] [Review][l:4] is completed and changes are approved
    - [ ] FCM (final commit message) is approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: /CONTRIBUTING.md#code-style
[l:3]: /CHANGELOG.md
[l:4]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2024-02-19 08:25 UTC, rogurotus commented
## FCM

```
Implement getCapabilities (#137)

Additionally:
- implement setCodecPreferences
- upgrade libwebrt to 121.0.6167.160
```

2024-02-26 14:02 UTC, evdokimovs requested changes

2024-02-26 14:02 UTC, evdokimovs commented on android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/WebrtcVideoEncoderFactory.kt
> +    return swFactory.queryCodecSupport(codecInfo, scalability)
Why `queryCodecSupport` uses only `swFactory`?

2024-02-26 14:02 UTC, evdokimovs commented on crates/libwebrtc-sys/src/bridge.rs
> +    #[repr(u8)]
Documentation should be written before attributes.

2024-02-26 14:02 UTC, evdokimovs commented on crates/libwebrtc-sys/src/bridge.rs
> +        TRANSPORT_CC,
Add docs about meaning of this types.

2024-02-26 14:02 UTC, evdokimovs commented on crates/libwebrtc-sys/src/lib.rs
> +/// `NACK` or `CCM` feedback.
Why only `NACK` and `CCM` if `RtcpFeedbackType` also has these variants:

```
CCM,
LNTF, // "goog-lntf"
NACK,
REMB, // "goog-remb"
TRANSPORT_CC,
```

2024-02-26 14:02 UTC, evdokimovs commented on crates/libwebrtc-sys/src/lib.rs
> +            .map(|v| webrtc::RtcpFeedbackMessageType::try_from(v).unwrap())
This `unwrap` looks suspicious. What if some new message type will be added to the `libwebrtc`'s enum? Maybe we can make something with it?

2024-02-26 14:02 UTC, evdokimovs commented on crates/native/src/api.rs
> +/// NACK or CCM feedback.
Same here:

> Why only `NACK` and `CCM` if `RtcpFeedbackType` also has these variants:
> 
> ```
> CCM,
> LNTF, // "goog-lntf"
> NACK,
> REMB, // "goog-remb"
> TRANSPORT_CC,
> ```

2024-02-26 14:02 UTC, evdokimovs commented on crates/native/src/api.rs
> +#[allow(clippy::upper_case_acronyms)]
I think that it's better to listen to Clippy and use native to Rust naming here.

2024-02-26 14:02 UTC, evdokimovs commented on lib/src/api/transceiver.dart
> +  // todo
What this todo is about?

2024-02-27 11:10 UTC, rogurotus commented on android/src/main/kotlin/com/instrumentisto/medea_flutter_webrtc/WebrtcVideoEncoderFactory.kt
> +    return swFactory.queryCodecSupport(codecInfo, scalability)
Fixed

2024-02-27 11:10 UTC, rogurotus commented on crates/libwebrtc-sys/src/bridge.rs
> +        TRANSPORT_CC,
Fixed

2024-02-27 11:10 UTC, rogurotus commented on crates/libwebrtc-sys/src/lib.rs
> +/// `NACK` or `CCM` feedback.
Fixed

2024-02-27 11:11 UTC, rogurotus commented on crates/libwebrtc-sys/src/lib.rs
> +            .map(|v| webrtc::RtcpFeedbackMessageType::try_from(v).unwrap())
Wrapped in `OptionRtcpFeedbackMessageType`. It is checked at the compilation stage

2024-02-27 11:12 UTC, rogurotus commented on crates/native/src/api.rs
> +/// NACK or CCM feedback.
Fixed

2024-02-27 11:12 UTC, rogurotus commented on crates/native/src/api.rs
> +#[allow(clippy::upper_case_acronyms)]
Fixed

2024-02-27 11:12 UTC, rogurotus commented on lib/src/api/transceiver.dart
> +  // todo
Deleted

2024-03-25 11:01 UTC, evdokimovs approved these changes

2024-03-25 17:14 UTC, tyranron approved these changes
@rogurotus @evdokimovs please do not forget CHANGELOG next time (you have that in checklist!) and be more pedantic regarding docs.

2024-03-25 18:41 UTC, merged