Fix iOS integration tests
instrumentisto/medea-flutter-webrtc pull request #162
Opened 2024-06-10 13:46 UTC by evdokimovs

## Synopsis

Currently our iOS integration tests are not working (especially in CI), so this PR fixes this problem.

## Solution

The problem occurs because iOS Simulator segfault on try to write some audio to the output audio device when `AVAudioSession` is not set to `active`.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains issue reference
    - [x] Has type and `k::` labels applied
    - [x] Has assignee
- Before [review][l:4]:
    - [x] Documentation is updated (if required)
    - [x] Tests are updated (if required)
    - [x] Changes conform [code style][l:2]
    - [x] [CHANGELOG entry][l:3] is added (if required)
    - [x] FCM (final commit message) is posted or updated
    - [x] [Draft mode][l:1] is removed
- [x] [Review][l:4] is completed and changes are approved
    - [x] FCM (final commit message) is approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: /CONTRIBUTING.md#code-style
[l:3]: /CHANGELOG.md
[l:4]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2024-07-02 09:52 UTC, evdokimovs commented
## FCM

```md
Fix iOS integration tests running on CI (#162)
```

2024-07-02 09:59 UTC, alexlapa approved these changes

2024-07-02 12:33 UTC, tyranron requested changes
@evdokimovs please renew the libwebrtc version everywhere. I pushed the changes, but there are some problems with hashes.

2024-07-25 11:53 UTC, evdokimovs commented
## FCM

```md
Fix iOS integration tests (#162)

Additionally:
- upgrade `libwebrtc-bin` to `126.0.6478.182-r2`
```

2024-07-25 12:26 UTC, tyranron approved these changes

2024-07-25 12:59 UTC, merged